
/* Reset. */
// #define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
// #define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_LED GP17
// #define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 1000U

#define CHARYBDIS_CONFIG_SYNC
#define POINTING_DEVICE_AUTO_MOUSE_ENABLE
#ifdef POINTING_DEVICE_AUTO_MOUSE_ENABLE
    #define AUTO_MOUSE_DEFAULT_LAYER 10
    #define AUTO_MOUSE_TIME 250
    #define AUTO_MOUSE_DELAY 0
#endif
#define CHARYBDIS_DRAGSCROLL_REVERSE_Y
#define TAPPING_TOGGLE 1

#ifdef POINTING_DEVICE_TASK_THROTTLE_MS
    #undef POINTING_DEVICE_TASK_THROTTLE_MS
    #define POINTING_DEVICE_TASK_THROTTLE_MS 2
#endif
#define CHARYBDIS_MINIMUM_DEFAULT_DPI 400
#define CHARYBDIS_DEFAULT_DPI_CONFIG_STEP 150
#define CHARYBDIS_MINIMUM_SNIPING_DPI 200
#define CHARYBDIS_SNIPING_DPI_CONFIG_STEP 100
#define CHARYBDIS_DRAGSCROLL_DPI 200
#define CHARYBDIS_DRAGSCROLL_BUFFER_SIZE 3

#undef MASTER_LEFT
#define MASTER_RIGHT

// #define MASTER_LEFT
#ifdef MASTER_LEFT
    #undef MASTER_RIGHT
    #define SPLIT_POINTING_ENABLE
    #define POINTING_DEVICE_RIGHT
#endif