#define CHARYBDIS_CONFIG_SYNC
#define POINTING_DEVICE_AUTO_MOUSE_ENABLE
#define AUTO_MOUSE_DEFAULT_LAYER 10
#define AUTO_MOUSE_TIME 500
#define AUTO_MOUSE_DELAY 0
#define CHARYBDIS_DRAGSCROLL_REVERSE_Y
#define TAPPING_TOGGLE 1

// #undef POINTING_DEVICE_TASK_THROTTLE_MS
// #define POINTING_DEVICE_TASK_THROTTLE_MS 

