#define CHARYBDIS_CONFIG_SYNC
#define POINTING_DEVICE_AUTO_MOUSE_ENABLE
#define AUTO_MOUSE_DEFAULT_LAYER 10
#define AUTO_MOUSE_TIME 400
// #define AUTO_MOUSE_DELAY TAPPING_TERM
#define CHARYBDIS_DRAGSCROLL_REVERSE_Y
